routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\LoginController; 
use App\Http\Controllers\DashboardController; 

/* PRODUCT */
use App\Http\Controllers\CategoryController; 
use App\Http\Controllers\UnitController; 
use App\Http\Controllers\ProductController; 

/*  PEOPLE */
use App\Http\Controllers\MemberController; 
use App\Http\Controllers\UserController; 

/*  SUPPLIER */
use App\Http\Controllers\SupplierController; 

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Route::get('/login', [LoginController::class, 'index'])->name('login');
Route::post('/login', [LoginController::class, 'authenticate'])->name('login.authenticate');
Route::get('/logout', [LoginController::class, 'logout'])->name('logout');

Route::middleware(['auth'])->group(function () {

    Route::get('/', [DashboardController::class, 'index'])->name('dashboard.index');

    //Category
    Route::resource('/categories', CategoryController::class);
    Route::post('/category/data', [CategoryController::class, 'data'])->name('category.data');

    // Unit
    // Route::resource('/units', UnitController::class);
    // Route::post('/unit/data', [UnitController::class, 'data'])->name('unit.data');

    // Product
    Route::resource('/products', ProductController::class);
    Route::post('/product/data', [ProductController::class, 'data'])->name('product.data');

    // Member
    Route::resource('/members', MemberController::class);
    Route::post('/member/data', [MemberController::class, 'data'])->name('member.data');

    // Supplier
    Route::resource('/suppliers', SupplierController::class);
    Route::post('/supplier/data', [SupplierController::class, 'data'])->name('supplier.data');

    // User
    Route::resource('/users', UserController::class);
    Route::post('/user/data', [UserController::class, 'data'])->name('user.data');

});

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    use HasFactory;

    protected $table = 'category';
    protected $primaryKey = 'id';
    protected $guarded = [];
    // protected $fillable = 'updated_at';

    // public $timestamps = true;

    public function product()
    {
        return $this->hasMany(Product::class);
    }
}

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    use HasFactory;

    protected $table = 'product';
    protected $primaryKey = 'id';
    protected $guarded = [];

    public function category(): HasOne
    {
        return $this->belongsTo(Category::class, 'category_id', 'id');
    }

}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Category;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $category['category'] = Category::get();
        return view('product.category.index')->with($category);
    }

    public function data() 
    {
        $category = Category::orderBy('id', 'DESC')->get();

        return datatables()
            ->of($category)
            ->addIndexColumn()
            ->addColumn('created_at', function ($category) {
                return $category->created_at->format('d M Y');
            })
            ->addColumn('last_updated', function ($category) {
                return $category->updated_at->diffForHumans();
            })
            ->addColumn('aksi', function ($category) {
                return '
                    <button data-category="'.$category->category_name.'" data-route="'. route('categories.update', $category->id) .'" class="edit btn btn-xs btn-success btn-flat"><i class="bi bi-pencil-square"></i></button>
                    <button onclick="deleteData(`'. route('categories.destroy', $category->id) .'`)" class="btn btn-xs btn-danger btn-flat delete"><i class="bi bi-trash"></i></button>
                ';
            })
            ->rawColumns(['aksi'])
            ->make(true);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validate = $request->validate([
            'category_name' => 'required|max:225|unique:category',
        ]);

        $name = $request['category_name'];

        $category = new Category;
        $category->category_name = $name;
        $category->save();

        return redirect()->route('categories.index')->with(['success' => 'Berhasil Disimpan!']);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validate = $request->validate([
            'category_name' => 'max:225|unique:category',
        ]);

        $name = $request['category_name'];

        $category = Category::find($id);
        $category->category_name = $name;
        $category->updated_at = now();
        $category->update();

        return redirect()->route('categories.index')->with(['success' => 'Berhasil di Update!']);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Category::find($id)->delete();
        return redirect()->route('categories.index')->with(['success' => 'Berhasil di Hapus!']);
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Product;
use App\Models\Category;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // $category['category'] = Category::get();
        $category = Category::all()->pluck('id', 'category_name');
        return view('product.data.index', compact('category'));
    }

    public function checkPrice($value)
    {
        if (gettype($value) == "string") {
            $temp = 0;
            for ($i = 0; $i < strlen($value); $i++) {
                if ((isset($value[$i]) == true && $value[$i] != ".") && $value[$i] != ",") {
                    $temp = ($temp * 10) + (int)$value[$i];
                }
            }
            return $temp;
        } else {
            return $value;
        }
    }

    public function data()
    {
        $product = Product::leftJoin('category', 'category.id', 'product.category_id')
                    ->select('product.*', 'category_name')     
                    ->orderBy('id', 'desc')
                    ->get();

        return datatables()
            ->of($product)
            ->addIndexColumn()
            ->addColumn('barcode', function ($product) {
                return '<span class="badge badge-info">'. $product->barcode .'</span>';
            })
            ->addColumn('purchase', function ($product) {
                return 'Rp. '. format_uang($product->purchase);
            })
            ->addColumn('sell', function ($product) {
                return 'Rp. '. format_uang($product->sell);
            })
            ->addColumn('stock', function ($product) {
                if($product->stock == 0)
                {
                    return '<span class="badge badge-danger">Habis</span>';
                }
                else{
                    return format_uang($product->stock);
                }
            })
            ->addColumn('created_at', function ($product) {
                return $product->created_at->format('d M Y');
            })
            ->addColumn('last_updated', function ($product) {
                return $product->updated_at->diffForHumans();
            })
            ->addColumn('action', function($product) { 
                return '
                    <button data-product="'.$product->product_name.'"
                            data-category="'.$product->category_id.'"
                            data-purchase="'.$product->purchase.'"
                            data-sell="'.$product->sell.'"
                            data-stock="'.$product->stock.'"
                            data-route="'. route('products.update', $product->id) .'" 
                            class="edit btn btn-xs btn-success btn-flat"><i class="bi bi-pencil-square"></i></button>
                    <button onclick="deleteForm(`'. route('products.destroy', $product->id) .'`)" class="btn btn-xs btn-danger btn-flat"><i class="bi bi-trash"></i></button>
                    '; 
                })
            ->rawColumns(['action', 'barcode'])
            ->make(true);
    }


    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $product = Product::select('barcode')->orderBy('created_at', 'DESC')->first();
        
        $barcode = '';

        if($product == NULL) {
            $barcode = 'B-0001';
        } else {
            $barcode = sprintf('B-000%03d', substr($product->barcode, 5) + 1);
            // $kode = sprintf('BRC-202205%03d' + 1);
        }

        $sell = ($this->checkPrice($request->purchase) * 0.2) + $this->checkPrice($request->purchase);

        $request['barcode'] = $barcode;
        $request['purchase'] = $this->checkPrice($request->purchase);
        $request['sell'] = $sell;

        $product = Product::create($request->all())->save();

        return redirect()->route('products.index')->with(['success' => 'Berhasil Disimpan!']);

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $product = Product::find($id);
        $product->update($request->all());

        return redirect()->route('products.index')->with(['success' => 'Berhasil Diupdate!']);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Product::find($id)->delete();
        return redirect()->route('products.index')->with(['success' => 'Berhasil dihapus!']);
    }
}

resources/views/product/category/form.blade.php
<!-- Modal -->
<div class="modal fade" id="modal-form" tabindex="-1" role="dialog"
    aria-labelledby="exampleModalLabelLogout" aria-hidden="true">
    <div class="modal-dialog" role="document">

        <form action="" method="post" class="form-horizontal">
            @csrf
            @method('post')

            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabelLogout">Ohh No!</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="form-group row">
                        <label for="category_name" class="col-md-2 col-md-offset-1 control-label">
                            <h5 class="my-2">Kategori</h5>
                        </label>
                        <div class="col-md-10">
                            <input type="text" name="category_name" id="category_name" class="form-control" required autofocus>
                            <div id="category_name" class="invalid-feedback">
                                Must be a Unique.
                            </div>
                            <span class="help-block with-errors"></span>
                        </div>
                        <p class="help">The name of Unit must be Unique!</p>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-outline-primary" data-dismiss="modal">Cancel</button>
                    <button type="submit" class="btn btn-primary"><i class="fa fa-circle-check"></i>
                    Simpan</button>
                </div>
            </div>
        </form>
    </div>
</div>

resources/views/product/category/index.blade.php
@extends('templates.layout')

@section('title')
    Data Kategori
@endsection

@section('breadcrumb')
@parent
    Kategori
@endsection

@section('content')
<div class="row mx-3">
    <div class="col-md-12 p-2 mb-3" style="background-color: white">
        <div class="box">

            <div class="box-header with-border mb-3">
                <button onclick="addForm('{{ route('categories.store') }}')" class="btn btn-primary mx-2 my-3"><i
                        class="fa fa-plus-circle"></i>
                    Tambah</button>
            </div>

            <div class="box-body table-responsive">
                <!-- DataTable with Hover -->
                <div class="col-lg-12">
                    <div class="card mb-4">
                        <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                            <h6 class="m-0 font-weight-bold text-primary">Showing All Data from Database - Category</h6>
                        </div>
                        <div class="table-responsive p-3">
                            <table class="table align-items-center table-flush table-hover text-center" id="dataTableHover">
                                <thead class="thead-light">
                                    <tr>
                                        <th width="8%" class="text-center">No</th>
                                        <th width="15%" class="text-center">Name</th>
                                        <th width="14%" class="text-center">Created At</th>
                                        <th width="14%" class="text-center">Last Updated</th>
                                        <th width="15%" class="text-center">Action</th>
                                    </tr>
                                </thead>
                            </table>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>
@includeIf('product.category.form')
@endsection

@push('scripts')
    <script>
        $('#success-alert').fadeTo(1500, 500).slideUp(500, function() {
            $('#success-alert').slideUp(500);
        });
        
        $('#danger-alert').fadeTo(1500, 500).slideUp(500, function() {
            $('#danger-alert').slideUp(500);
        });

        $('#modal-form').on('show.bs.modal', function(e) {
            
        })

        // $('#dataProduk').DataTable();

        // $(document).ready( function () {
        //     $('#dataTableHover').DataTable();
        // } );

        // $('.delete').on('click', function(e) {
        //     e.preventDefault()

        //     Swal.fire({
        //         title: 'Are you sure?',
        //         text: "You won't be able to revert this!",
        //         icon: 'warning',
        //         showCancelButton: true,
        //         confirmButtonColor: '#3085d6',
        //         cancelButtonColor: '#d33',
        //         confirmButtonText: 'Yes, delete it!',

        //         }).then((result) => {
        //         if (result.isConfirmed) {
        //             $(e.target).closest('form').submit()
        //         }else swal.close()
        //     })
        // });

        function addForm(url) {
            $('#modal-form').modal('show')
            $('#modal-form .modal-title').text('Tambah Kategori Baru');
        }

        let table;
            table = $('.table').DataTable({
            processing: true,
            responsive: true,
            autoWidth: false,
            serverSide: true,
            ajax: {
                url: "{{ route('category.data') }}",
                type: "POST",
                data: {  
                    _token: '{{ csrf_token() }}'
                }
            },
            columns: [
                {data:'DT_RowIndex', searchable: false, sortable: false},
                {data:'category_name'},
                {data:'created_at'},
                {data:'last_updated'},
                {data:'aksi', searchable: false, sortable: false},
            ]
        });

        $(document).on('click', '.edit', function (event) {
            let category_name = $(this).data('category')
            let url = $(this).data('route')

            let data = {
                category_name : category_name,
                url: url
            }

            editForm(data)
        })
        
        function editForm(data) {
            $('#modal-form').modal('show')
            $('#modal-form .modal-title').text('Edit unit');

            $('#modal-form form')[0].reset();
            $('#modal-form form').attr('action', data.url);
            $('#modal-form [name=_method]').val('put');
            
            $('#modal-form [name=category_name]').val(data.category_name);
        }

        function deleteData(url) {
            Swal.fire({
                title: 'Are you sure?',
                text: "Data akan dihapus",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Yes, delete it!',
                }).then((result) => {
                if (result.isConfirmed) {
                    $.post(url, {
                        '_token': $('[name=token]').attr('content'),
                        '_method': 'delete'
                    })
                    .done((response) => {
                        Swal.fire({
                            title: 'Sukses!',
                            text: 'Data berhasil dihapus',
                            icon: 'success',
                            confirmButtonText: 'Lanjut',
                            confirmButtonColor: '#28A745'
                        }) 
                        table.ajax.reload();
                    })
                    .fail((errors) => {
                        Swal.fire({
                            title: 'Gagal!',
                            text: 'Data gagal dihapus',
                            icon: 'error',
                            confirmButtonText: 'Kembali',
                            confirmButtonColor: '#DC3545'
                        })                       
                        return;
                    });
                } else if (result.isDenied) {
                    Swal.fire({
                        title: 'Data batal dihapus',
                        icon: 'warning',
                    })
                }
            })
        }

    </script>    
@endpush