routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\LoginController; 
use App\Http\Controllers\DashboardController; 

/* PRODUCT */
use App\Http\Controllers\CategoryController; 
use App\Http\Controllers\UnitController; 
use App\Http\Controllers\ProductController; 

/*  PEOPLE */
use App\Http\Controllers\MemberController; 
use App\Http\Controllers\UserController; 

/*  SUPPLIER */
use App\Http\Controllers\SupplierController; 

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Route::get('/login', [LoginController::class, 'index'])->name('login');
Route::post('/login', [LoginController::class, 'authenticate'])->name('login.authenticate');
Route::get('/logout', [LoginController::class, 'logout'])->name('logout');

Route::middleware(['auth'])->group(function () {

    Route::get('/', [DashboardController::class, 'index'])->name('dashboard.index');

    //Category
    Route::resource('/categories', CategoryController::class);
    Route::post('/category/data', [CategoryController::class, 'data'])->name('category.data');

    // Unit
    // Route::resource('/units', UnitController::class);
    // Route::post('/unit/data', [UnitController::class, 'data'])->name('unit.data');

    // Product
    Route::resource('/products', ProductController::class);
    Route::post('/product/data', [ProductController::class, 'data'])->name('product.data');

    // Member
    Route::resource('/members', MemberController::class);
    Route::post('/member/data', [MemberController::class, 'data'])->name('member.data');

    // Supplier
    Route::resource('/suppliers', SupplierController::class);
    Route::post('/supplier/data', [SupplierController::class, 'data'])->name('supplier.data');

    // User
    Route::resource('/users', UserController::class);
    Route::post('/user/data', [UserController::class, 'data'])->name('user.data');

});

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    use HasFactory;

    protected $table = 'product';
    protected $primaryKey = 'id';
    protected $guarded = [];

    public function category(): HasOne
    {
        return $this->belongsTo(Category::class, 'category_id', 'id');
    }

}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Product;
use App\Models\Category;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // $category['category'] = Category::get();
        $category = Category::all()->pluck('id', 'category_name');
        return view('product.data.index', compact('category'));
    }

    public function checkPrice($value)
    {
        if (gettype($value) == "string") {
            $temp = 0;
            for ($i = 0; $i < strlen($value); $i++) {
                if ((isset($value[$i]) == true && $value[$i] != ".") && $value[$i] != ",") {
                    $temp = ($temp * 10) + (int)$value[$i];
                }
            }
            return $temp;
        } else {
            return $value;
        }
    }

    public function data()
    {
        $product = Product::leftJoin('category', 'category.id', 'product.category_id')
                    ->select('product.*', 'category_name')     
                    ->orderBy('id', 'desc')
                    ->get();

        return datatables()
            ->of($product)
            ->addIndexColumn()
            ->addColumn('barcode', function ($product) {
                return '<span class="badge badge-info">'. $product->barcode .'</span>';
            })
            ->addColumn('purchase', function ($product) {
                return 'Rp. '. format_uang($product->purchase);
            })
            ->addColumn('sell', function ($product) {
                return 'Rp. '. format_uang($product->sell);
            })
            ->addColumn('stock', function ($product) {
                if($product->stock == 0)
                {
                    return '<span class="badge badge-danger">Habis</span>';
                }
                else{
                    return format_uang($product->stock);
                }
            })
            ->addColumn('created_at', function ($product) {
                return $product->created_at->format('d M Y');
            })
            ->addColumn('last_updated', function ($product) {
                return $product->updated_at->diffForHumans();
            })
            ->addColumn('action', function($product) { 
                return '
                    <button data-product="'.$product->product_name.'"
                            data-category="'.$product->category_id.'"
                            data-purchase="'.$product->purchase.'"
                            data-sell="'.$product->sell.'"
                            data-stock="'.$product->stock.'"
                            data-route="'. route('products.update', $product->id) .'" 
                            class="edit btn btn-xs btn-success btn-flat"><i class="bi bi-pencil-square"></i></button>
                    <button onclick="deleteForm(`'. route('products.destroy', $product->id) .'`)" class="btn btn-xs btn-danger btn-flat"><i class="bi bi-trash"></i></button>
                    '; 
                })
            ->rawColumns(['action', 'barcode'])
            ->make(true);
    }


    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $product = Product::select('barcode')->orderBy('created_at', 'DESC')->first();
        
        $barcode = '';

        if($product == NULL) {
            $barcode = 'B-0001';
        } else {
            $barcode = sprintf('B-000%03d', substr($product->barcode, 5) + 1);
            // $kode = sprintf('BRC-202205%03d' + 1);
        }

        $sell = ($this->checkPrice($request->purchase) * 0.2) + $this->checkPrice($request->purchase);

        $request['barcode'] = $barcode;
        $request['purchase'] = $this->checkPrice($request->purchase);
        $request['sell'] = $sell;

        $product = Product::create($request->all())->save();

        return redirect()->route('products.index')->with(['success' => 'Berhasil Disimpan!']);

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $product = Product::find($id);
        $product->update($request->all());

        return redirect()->route('products.index')->with(['success' => 'Berhasil Diupdate!']);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Product::find($id)->delete();
        return redirect()->route('products.index')->with(['success' => 'Berhasil dihapus!']);
    }
}

resources/views/product/data/form.blade.php
<!-- Modal -->
<div class="modal fade" id="modal-form" tabindex="-1" role="dialog"
    aria-labelledby="exampleModalLabelLogout" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">

        <form action="" method="post" class="form-horizontal">
            @csrf
            @method('post')

            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabelLogout">Ohh No!</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="form-group row">
                        <label for="product_name" class="col-md-2 col-md-offset-1 control-label">
                            <h5 class="my-2">Nama Produk</h5>
                        </label>
                        <div class="col-md-10">
                            <input type="text" name="product_name" id="product_name" class="form-control" required autofocus>
                            <p class="help">The name of Product must be Unique!</p>
                            <div id="product_name" class="invalid-feedback">
                                Must be a Unique.
                            </div>
                            <span class="help-block with-errors"></span>
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="category_id" class="col-md-2 col-md-offset-1 control-label">
                            <h5 class="my-2">Kategori</h5>
                        </label>
                        <div class="col-md-10">
                            <select name="category_id" id="category_id" class="form-control" required>
                                <option value="">Pilih Kategori</option>
                                @foreach ($category as $key => $item )
                                    <option value="{{ $item }}">{{ $key }}</option>
                                @endforeach
                            </select>
                            <span class="help-block with-errors"></span>
                        </div>
                    </div>

                    <div class="input-group mb-3 mx-1"> 
                        <label for="purchase" style="margin-left: -16px; margin-right:17.6px;" class="col-md-2 control-label">
                            <h5 class="my-2">Harga Beli</h5> 
                        </label>
                        <div class="input-group-prepend"> 
                            <span class="input-group-text">RP.</span> 
                        </div> 
                        <input type="text" name="purchase" id="purchase" class="form-control" required placeholder="0" maxlength="20" aria-describedby="basic-addon1">
                        <span class="help-block with-errors"></span>
                    </div>

                    <div class="input-group mb-3 mx-1"> 
                        <label for="sell" style="margin-left: -16px; margin-right:17.6px;" class="col-md-2 control-label">
                            <h5 class="my-2">Harga Jual</h5> 
                        </label>
                        <div class="input-group-prepend "> 
                            <span class="input-group-text">RP.</span> 
                        </div> 
                        <input readonly type="text" name="sell" id="sell" class="form-control" required placeholder="0" maxlength="20" aria-describedby="basic-addon1">
                        <span class="help-block with-errors"></span>
                    </div>

                    <div class="form-group row">
                        <label for="stock" class="col-md-2 col-md-offset-1 control-label">
                            <h5 class="my-2">Stok</h5>
                        </label>
                        <div class="col-md-10">
                            <input type="number" name="stock" id="stock" class="form-control" required autofocus>
                            <span class="help-block with-errors"></span>
                        </div>
                    </div>

                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-outline-primary" data-dismiss="modal">Cancel</button>
                    <button type="submit" class="btn btn-primary"><i class="fa fa-circle-check"></i>
                    Simpan</button>
                </div>
            </div>
        </form>
    </div>
</div>

resources/views/product/data/index.blade.php
@extends('templates.layout')

@section('title')
    Data Produk
@endsection

@section('breadcrumb')
@parent
    Produk
@endsection

@section('content')
<div class="row mx-3">
    <div class="col-md-12 p-2 mb-3" style="background-color: white">
        <div class="box">

            <div class="box-header with-border mb-3">
                <button onclick="addForm('{{ route('products.store') }}')" class="btn btn-primary mx-2 my-3"><i
                        class="fa fa-plus-circle"></i>
                    Tambah</button>
            </div>

            <div class="box-body table-responsive">
                <!-- DataTable with Hover -->
                <div class="col-lg-12">
                    <div class="card mb-4">
                        <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                            <h6 class="m-0 font-weight-bold text-primary">Showing All Data from Database - Product</h6>
                        </div>
                        <div class="table-responsive p-3">
                            <table class="table align-items-center table-flush table-hover text-center" id="dataTableHover">
                                <thead class="thead-light">
                                    <tr>
                                        <th width="6%" class="text-center">No</th>
                                        <th width="6%" class="text-center">Barcode</th>
                                        <th width="15%" class="text-center">Name</th>
                                        <th width="15%" class="text-center">Category</th>
                                        <th width="15%" class="text-center">Purchase</th>
                                        <th width="15%" class="text-center">Sell</th>
                                        <th width="8%" class="text-center">Stock</th>
                                        <th width="14%" class="text-center">Created At</th>
                                        <th width="14%" class="text-center">Last Updated</th>
                                        <th width="20%" class="text-center">Action</th>
                                    </tr>
                                </thead>
                            </table>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>
@includeIf('product.data.form')
@endsection

@push('scripts')
    <script>
        $('#success-alert').fadeTo(1500, 500).slideUp(500, function() {
            $('#success-alert').slideUp(500);
        });
        
        $('#danger-alert').fadeTo(1500, 500).slideUp(500, function() {
            $('#danger-alert').slideUp(500);
        });


        function formatRupiah(angka, prefix){
            var number_string   = angka.replace(/[^,\d]/g, '').toString(),
            split               = number_string.split(','),
            sisa                = split[0].length % 3,
            rupiah              = split[0].substr(0, sisa),
            ribuan              = split[0].substr(sisa).match(/\d{3}/gi);

            if(ribuan){
                separator = sisa ? '.' : '';
                rupiah += separator + ribuan.join('.');
            }

            rupiah = split[1] != undefined ? rupiah + ',' + split[1] : rupiah;
            return prefix == undefined ? rupiah : (rupiah ? '' + rupiah : '');
        }

        function generateRupiah(elemValue) {
            return $(elemValue).val(formatRupiah($(elemValue).val(), 'Rp. '))
        }

        $(document).on('keyup', '#purchase', function(e){
            generateRupiah(this);
        })
        $(document).on('keyup', '#sell', function(e){
            generateRupiah(this);
        })


        function addForm(url) {
            $('#modal-form').modal('show')
            $('#modal-form .modal-title').text('Tambah Produk Baru');
        }

        let table;
            table = $('.table').DataTable({
            processing: true,
            responsive: true,
            autoWidth: false,
            serverSide: true,
            ajax: {
                url: "{{ route('product.data') }}",
                type: "POST",
                data: {  
                    _token: '{{ csrf_token() }}'
                }
            },
            columns: [
                {data:'DT_RowIndex', searchable: false, sortable: false},
                {data:'barcode'},
                {data:'product_name'},
                {data:'category_name'},
                {data:'purchase'},
                {data:'sell'},
                {data:'stock'},
                {data:'created_at'},
                {data:'last_updated'},
                {data:'action', searchable: false, sortable: false},
            ]
        });
        
        $(document).on('click', '.edit', function (event) {
            let product_name = $(this).data('product')
            let category_id = $(this).data('category_id')
            let purchase = $(this).data('purchase')
            let sell = $(this).data('sell')
            let stock = $(this).data('stock')
            let url = $(this).data('route')

            let data = {
                product_name : product_name,
                category_id : category_id,
                purchase : purchase,
                sell : sell,
                stock : stock,
                url: url
            }

            editForm(data)
        })
        
        function editForm(data) {
            $('#modal-form').modal('show')
            $('#modal-form .modal-title').text('Edit Produk');

            $('#modal-form form')[0].reset();
            $('#modal-form form').attr('action', data.url);
            $('#modal-form [name=_method]').val('put');
            
            $('#modal-form [name=product_name]').val(data.product_name);
            $('#modal-form [name=category_id]').val(data.category_id);
            $('#modal-form [name=purchase]').val(data.purchase);
            $('#modal-form [name=sell]').val(data.sell);
            $('#modal-form [name=stock]').val(data.stock);
        }

        function deleteForm(url) {
            Swal.fire({
                title: 'Are you sure?',
                text: "Data akan dihapus",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Yes, delete it!',
                }).then((result) => {
                if (result.isConfirmed) {
                    $.post(url, {
                        '_token': $('[name=token]').attr('content'),
                        '_method': 'delete'
                    })
                    .done((response) => {
                        Swal.fire({
                            title: 'Sukses!',
                            text: 'Data berhasil dihapus',
                            icon: 'success',
                            confirmButtonText: 'Lanjut',
                            confirmButtonColor: '#28A745'
                        }) 
                        table.ajax.reload();
                    })
                    .fail((errors) => {
                        Swal.fire({
                            title: 'Gagal!',
                            text: 'Data gagal dihapus',
                            icon: 'error',
                            confirmButtonText: 'Kembali',
                            confirmButtonColor: '#DC3545'
                        })                       
                        return;
                    });
                } else if (result.isDenied) {
                    Swal.fire({
                        title: 'Data batal dihapus',
                        icon: 'warning',
                    })
                }
            })
        }
    
    </script>    
@endpush