routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\LoginController; 
use App\Http\Controllers\DashboardController; 

/* PRODUCT */
use App\Http\Controllers\CategoryController; 
use App\Http\Controllers\UnitController; 
use App\Http\Controllers\ProductController; 

/*  PEOPLE */
use App\Http\Controllers\MemberController; 
use App\Http\Controllers\UserController; 

/*  SUPPLIER */
use App\Http\Controllers\SupplierController; 

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Route::get('/login', [LoginController::class, 'index'])->name('login');
Route::post('/login', [LoginController::class, 'authenticate'])->name('login.authenticate');
Route::get('/logout', [LoginController::class, 'logout'])->name('logout');

Route::middleware(['auth'])->group(function () {

    Route::get('/', [DashboardController::class, 'index'])->name('dashboard.index');

    //Category
    Route::resource('/categories', CategoryController::class);
    Route::post('/category/data', [CategoryController::class, 'data'])->name('category.data');

    // Unit
    // Route::resource('/units', UnitController::class);
    // Route::post('/unit/data', [UnitController::class, 'data'])->name('unit.data');

    // Product
    Route::resource('/products', ProductController::class);
    Route::post('/product/data', [ProductController::class, 'data'])->name('product.data');

    // Member
    Route::resource('/members', MemberController::class);
    Route::post('/member/data', [MemberController::class, 'data'])->name('member.data');

    // Supplier
    Route::resource('/suppliers', SupplierController::class);
    Route::post('/supplier/data', [SupplierController::class, 'data'])->name('supplier.data');

    // User
    Route::resource('/users', UserController::class);
    Route::post('/user/data', [UserController::class, 'data'])->name('user.data');

});

app/Models/Supplier.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Supplier extends Model
{
    use HasFactory;

    protected $table = 'supplier';
    protected $primaryKey = 'id';
    protected $guarded = [];
}

app/Http/Controllers/SupplierController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Supplier;

class SupplierController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('supplier.index');
    }

    public function data() 
    {
        $supplier = Supplier::orderBy('id', 'DESC')->get();

        return datatables()
            ->of($supplier)
            ->addIndexColumn()
            ->addColumn('company', function ($supplier) {
                return '<div style="align-items:left">'. $supplier->company .'</div>';
            })
            ->addColumn('created_at', function ($supplier) {
                return $supplier->created_at->format('d M Y');
            })
            ->addColumn('last_updated', function ($supplier) {
                return $supplier->updated_at->diffForHumans();
            })
            ->addColumn('aksi', function ($supplier) {
                return '
                    <button data-name="'.$supplier->name.'" data-adress="'.$supplier->adress.'" data-company="'.$supplier->company.'" data-route="'. route('members.update', $supplier->id) .'" class="edit btn btn-xs btn-success btn-flat"><i class="bi bi-pencil-square"></i></button>
                    <button onclick="deleteData(`'. route('members.destroy', $supplier->id) .'`)" class="btn btn-xs btn-danger btn-flat delete"><i class="bi bi-trash"></i></button>
                ';
            })
            ->rawColumns(['aksi', 'company'])
            ->make(true);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $supplier = new Supplier;
        $supplier->name = $request->name;
        $supplier->adress = $request->adress;
        $supplier->company = $request->company;
        $supplier->save();

        return redirect()->route('suppliers.index')->with(['success', 'Berhasil Disimpan']);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $supplier = Supplier::find($id);
        $supplier->name = $request->name;
        $supplier->adress = $request->adress;
        $supplier->company = $request->company;
        $supplier->update();

        return redirect()->route('suppliers.index')->with(['success', 'Berhasil Diperbarui!']);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Supplier::find($id)->destroy();
        return redirect()->route('suppliers.index')->with(['success', 'Berhasil Dihapus!']);
    }
}

resources/views/supplier/form.blade.php
<!-- Modal -->
<div class="modal fade" id="modal-form" tabindex="-1" role="dialog"
    aria-labelledby="exampleModalLabelLogout" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">

        <form action="" method="post" class="form-horizontal">
            @csrf
            @method('post')

            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabelLogout">Ohh No!</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="form-group row">
                        <label for="name" class="col-md-2 col-md-offset-1 control-label">
                            <h5 class="my-2">Nama</h5>
                        </label>
                        <div class="col-md-10">
                            <input type="text" name="name" id="name" class="form-control" required autofocus>
                            <span class="help-block with-errors"></span>
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="adress" class="col-md-2 col-md-offset-1 control-label">
                            <h5 class="my-2">Alamat</h5>
                        </label>
                        <div class="col-md-10">
                            <input type="text" name="adress" id="adress" class="form-control" required>
                            <span class="help-block with-errors"></span>
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="company" class="col-md-2 col-md-offset-1 control-label">
                            <h5 class="my-2">Perusahaan</h5>
                        </label>
                        <div class="col-md-10">
                            <input type="text" name="company" id="company" class="form-control" required>
                            <span class="help-block with-errors"></span>
                        </div>
                    </div>

                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-outline-primary" data-dismiss="modal">Cancel</button>
                    <button type="submit" class="btn btn-primary"><i class="fa fa-circle-check"></i>
                    Simpan</button>
                </div>
            </div>
        </form>
    </div>
</div>

resources/views/supplier/index.blade.php
@extends('templates.layout')

@section('title')
    Data Pemasok
@endsection

@section('breadcrumb')
@parent
    Pemasok
@endsection

@push('css')
    <style>
        .luxury {
            font-family: 'Poppins', sans-serif;
        }
    </style>
@endpush

@section('content')
<div class="row mx-3">
    <div class="col-md-12 p-2 mb-3" style="background-color: white">
        <div class="box">

            <div class="box-header with-border mb-3">
                <button onclick="addForm('{{ route('suppliers.store') }}')" class="btn btn-primary mx-2 my-3"><i
                        class="fa fa-plus-circle"></i>
                    Tambah</button>
            </div>

            <div class="box-body table-responsive">
                <!-- DataTable with Hover -->
                <div class="col-lg-12">
                    <div class="card mb-4">
                        <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                            <h6 class="m-0 font-weight-bold text-primary">Showing All Data from Database - Supplier</h6>
                        </div>
                        <div class="table-responsive p-3">
                            <table class="table align-items-center table-flush table-hover text-center" id="dataTableHover">
                                <thead class="thead-light">
                                    <tr>
                                        <th width="8%" class="text-center">No</th>
                                        <th width="15%" class="text-center">Name</th>
                                        <th width="15%" class="text-center">Adress</th>
                                        <th width="15%" class="text-center">Company</th>
                                        <th width="14%" class="text-center">Created At</th>
                                        <th width="14%" class="text-center">Last Updated</th>
                                        <th width="15%" class="text-center">Action</th>
                                    </tr>
                                </thead>
                            </table>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>
@includeIf('supplier.form')
@endsection

@push('scripts')
    <script>
        $('#success-alert').fadeTo(1500, 500).slideUp(500, function() {
            $('#success-alert').slideUp(500);
        });
        
        $('#danger-alert').fadeTo(1500, 500).slideUp(500, function() {
            $('#danger-alert').slideUp(500);
        });


        function addForm(url) {
            $('#modal-form').modal('show')
            $('#modal-form .modal-title').text('Tambah Pemasok Baru');
        }

        let table;
            table = $('.table').DataTable({
            processing: true,
            responsive: true,
            autoWidth: false,
            serverSide: true,
            ajax: {
                url: "{{ route('supplier.data') }}",
                type: "POST",
                data: {  
                    _token: '{{ csrf_token() }}'
                }
            },
            columns: [
                {data:'DT_RowIndex', searchable: false, sortable: false},
                {data:'name'},
                {data:'adress'},
                {data:'company'},
                {data:'created_at'},
                {data:'last_updated'},
                {data:'aksi', searchable: false, sortable: false},
            ]
        });

        $(document).on('click', '.edit', function (event) {
            let name = $(this).data('name')
            let adress = $(this).data('adress')
            let level = $(this).data('level')
            let company = $(this).data('company')
            let url = $(this).data('route')

            let data = {
                name : name,
                adress : adress,
                level : level,
                company : company,
                url: url
            }

            editForm(data)
        })
        
        function editForm(data) {
            $('#modal-form').modal('show')
            $('#modal-form .modal-title').text('Edit Pemasok');

            $('#modal-form form')[0].reset();
            $('#modal-form form').attr('action', data.url);
            $('#modal-form [name=_method]').val('put');
            
            $('#modal-form [name=name]').val(data.name);
            $('#modal-form [name=adress]').val(data.adress);
            $('#modal-form [name=level]').val(data.level);
            $('#modal-form [name=company]').val(data.company);
        }

        function deleteData(url) {
            Swal.fire({
                title: 'Are you sure?',
                text: "Data akan dihapus",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Yes, delete it!',
                }).then((result) => {
                if (result.isConfirmed) {
                    $.post(url, {
                        '_token': $('[name=token]').attr('content'),
                        '_method': 'delete'
                    })
                    .done((response) => {
                        Swal.fire({
                            title: 'Sukses!',
                            text: 'Data berhasil dihapus',
                            icon: 'success',
                            confirmButtonText: 'Lanjut',
                            confirmButtonColor: '#28A745'
                        }) 
                        table.ajax.reload();
                    })
                    .fail((errors) => {
                        Swal.fire({
                            title: 'Gagal!',
                            text: 'Data gagal dihapus',
                            icon: 'error',
                            confirmButtonText: 'Kembali',
                            confirmButtonColor: '#DC3545'
                        })                       
                        return;
                    });
                } else if (result.isDenied) {
                    Swal.fire({
                        title: 'Data batal dihapus',
                        icon: 'warning',
                    })
                }
            })
        }

    </script>    
@endpush